### ISSUE TITLE
Could you public your pretrained pig detection model

### ISSUE THREAD

**Issue by sangtv9** [AIFARMS/multi-camera-pig-tracking#1]
Thanks for you great project. I am building a system that can count pig. So can you help me, provide the pretrained weight of pig detection model.

**Comment by ani8897** [comment]
You can find the weights here: https://drive.google.com/file/d/1SCDtxM2WXQBMx1pqeoOg5JpYK3GvfDvx/view?usp=sharing

You can follow this README to annotate your images using the pre-trained weights: https://github.com/AIFARMS/multi-camera-pig-tracking/blob/master/deepsort-tracking/yolov4/README.md

Please let me know if you face any more issues
