### ISSUE TITLE
Can we use this for realtime cameras for person tracking?

### ISSUE THREAD

**Issue by Ritesh1991** [AIFARMS/multi-camera-pig-tracking#2]
Hi I want to implement for person tracking and reid. yolo model i need to change can you tell what i need to change for reid in your code.what i need to do to track more than two cameras

**Comment by ani8897** [comment]
We are doing Re-ID by using homography. Firstly, you will need to modify the YOLO model to detect people. Then depending on your camera setup, you will need to modify the homography matrices. You can follow this workshop for more information: https://iccv2021-mmp.github.io/

**Comment by Hemilibeatriz** [comment]
Hi @Ritesh1991 

Did you proceed with that research? Did your implementation for identifying people across multiple cameras work out?
