### ISSUE TITLE
Error in running manager.py

### ISSUE THREAD

**Issue by kruthikakr** [AIFARMS/multi-camera-pig-tracking#3]
Hi
I am following the steps to running the code .I found missing packages
Run any one of the commands from commands.txt, for instance: python3 manager.py --av data/multicam-dataset/0/0-Pen_B.mp4 --cv data/multicam-dataset/0/0-Ceiling_Cam.mp4 --cj data/multicam-dataset/0/0-Ceiling_Cam.json --aj data/multicam-dataset/0/0-Pen_B.json --cl 457

ModuleNotFoundError: No module named 'disjoint_set'

Any help for this ?? 
Thanks you.

**Comment by ani8897** [comment]
You will need to install that package from here: https://pypi.org/project/disjoint-set/
