### ISSUE TITLE
error with darknet

### ISSUE THREAD

**Issue by trituenhantaovn** [AIFARMS/multi-camera-pig-tracking#4]
when I run tracker_cv2.py 
errors appear

![image](https://user-images.githubusercontent.com/92193946/137478974-35beb7d8-f7c2-41c9-8323-13bc1d8d9a09.png)

please help me, thanks you.

**Comment by trituenhantaovn** [comment]
can you provide the requirement environment file?

**Comment by vangjin** [comment]
i have the same problem, did you solve it?

**Comment by ani8897** [comment]
You can lookup https://github.com/AlexeyAB/darknet to compile darknet on your machine.
