### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by GenjiCy** [AIFARMS/multi-camera-pig-tracking#5]
I would like to use this model for multiple-camera people-trakcing, but i see none training-guide. Is this could just use yolo-format labels to train?

**Comment by Ayushpanchratan** [comment]
How to train this model on custom dataset ??

**Comment by ani8897** [comment]
You can use any custom object detector and tracker for detecting and tracking people with bounding boxes in a single camera view.

For multi-camera tracking, this method uses the homography between the two camera views for associating tracking IDs across views. Please refer to the `Homography Estimation` section in https://arxiv.org/pdf/2111.10971.pdf for more details.
